# Generated by Django 4.2.4 on 2023-08-24 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkInProgress',
        ),
    ]
